### ISSUE TITLE
Is there any way to hide JwtTokenProvider#validateToken exception info on console?

### ISSUE THREAD

**Issue by dhb52** [murraco/spring-boot-jwt#3]
When comes to token validation error, the console prints out exception info.

```
murraco.exception.CustomException: Expired or invalid JWT token
        at murraco.security.JwtTokenProvider.validateToken(JwtTokenProvider.java:87) ~[classes/:na]
        at murraco.security.JwtTokenFilter.doFilter(JwtTokenFilter.java:28) ~[classes/:na]
       ...
```

```
JwtTokenProvider. 
 public boolean validateToken(String token) {
    try {
      Jwts.parser().setSigningKey(secretKey).parseClaimsJws(token);
      return true;
    } catch (JwtException | IllegalArgumentException e) {
      throw new CustomException("Expired or invalid JWT token", HttpStatus.INTERNAL_SERVER_ERROR);
    }
}
```

It seems that ```GlobalExceptionHandlerController``` never called when doFilter throws an exception.

**Comment by dhb52** [comment]
[StackFlow Solution](https://stackoverflow.com/questions/30335157/make-simple-servlet-filter-work-with-controlleradvice)

> As specified by the java servlet specification Filters execute always before a Servlet is invoked. Now a @ControllerAdvice is only useful for controller which are executed inside the DispatcherServlet. So using a Filter and expecting a @ControllerAdvice or in this case the @ExceptionHandler, to be invoked isn't going to happen.
> 
> You need to either put the same logic in the filter (for writing a JSON response) or instead of a filter use a HandlerInterceptor which does this check. The easiest way is to extend the HandlerInterceptorAdapter and just override and implement the preHandle method and put the logic from the filter into that method.

PR:
[Merged PR](https://github.com/murraco/spring-boot-jwt/pull/4)
